### ISSUE TITLE
将空行时间轴替换为时间轴后面跟一个不可见字符，而不是删除

### ISSUE THREAD

**Issue by sf467** [coolight7/my_lyric#1]
但是如果可以不移除我给歌词加进去的空行歌词就更好了
(・へ・)

**Comment by coolight7** [comment]
- hh这个库确实是有参数可以支持不移除空行的
- 但拟声那边的设计不好改

**Comment by sf467** [comment]
> * hh这个库确实是有参数可以支持不移除空行的
> 
>     * 但拟声那边的设计不好改

QAQ
